# Generated by Django 3.2.9 on 2021-11-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='description')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='photo')),
                ('rating', models.SmallIntegerField(verbose_name='rating')),
                ('data', models.DateTimeField(verbose_name='data')),
            ],
        ),
    ]
